server:
  port: 8888
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    git:
      mode: full
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: config-server
  profiles:
    active: native, awss3
  cloud:
    config:
      server:
        accept-empty: false
        awss3:
          bucket: ${CONFIG_SERVER_BUCKET}
          region: ${CONFIG_SERVER_REGION}
          order: 2
        native:
          search-locations: ${CONFIG_SERVER_SEARCH_LOCATIONS}
          add-label-locations: true
          order: 1
  security:
    user:
      name: ${CONFIG_SERVER_SECURITY_USERNAME}
      password: ${CONFIG_SERVER_SECURITY_PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ${CONFIG_SERVER_AWS_ACCESS_KEY}
      secret-key: ${CONFIG_SERVER_AWS_SECRET_KEY}